// This file has been commented out to resolve the CS0101 duplication error.
// The actual VehicleTypes enum has already been generated by the plugin, 
// but the GLEY_TRAFFIC_SYSTEM define symbol was lost during the platform switch.

/*
#if !GLEY_TRAFFIC_SYSTEM
namespace Gley.TrafficSystem
{
    /// <summary>
    /// Temp script, it will be disabled when plugin is fully configured
    /// </summary>
    public enum VehicleTypes
    {
        Car,
    }
}
#endif
*/